# Use postgres/example user/password credentials
version: '3.3'

services:

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=chart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data